version: 2
orbs:
    cypress: cypress-io/cypress@1
    aws-s3: circleci/aws-s3@1.0.0

############################
jobs:
  # Run Cypress Tests
  test-cypress:
    docker:
      - image: cypress/base:12.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run cypress:circleci

  # Deploy to the staging S3 bucket
  deploy-staging:
    docker:
      - image: circleci/node:12.8.0-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test

      # setup stuff for AWS CLI deploy
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls

      - run: env REACT_APP_ENV='STAGING' npm run deploy

  # Deploy to the production S3 bucket
  deploy-prod:
    docker:
      - image: circleci/node:12.8.0-buster
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test

      # setup stuff for AWS CLI deploy
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls

      - run: env REACT_APP_ENV='PRODUCTION' npm run deploy

############################
workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test-cypress:
          filters:
            branches:
              ignore: # only test pushes/pulls to staging and master
                - develop
                - /feature-.*/
                - /bug-.*/
      - deploy-staging:
          requires:
            - test-cypress
          filters:
            branches:
              only: staging
      - deploy-prod:
          requires:
            - test-cypress # don't deploy unless tests pass
          filters:
            branches:
              only: master
